### ISSUE TITLE
Symfony framework detection

### ISSUE THREAD

**Issue by dragoonis** [newrelic/newrelic-php-agent#39]
Hey Newrelic / @joshuabenuck 

I've been reviewing the C code here. I see there's `fw_symfony.c` `fw_symfony2.c` and `fw_symfony4.c`.

Does the php extension auto-detect which version we're using? or do we have to tell it? More implementation-detail questions will follow once I know this answer. 

Thank you for your time.

**Comment by joshuabenuck** [comment]
It autodetects based on the files present. See this section of [php_execute.c](https://github.com/newrelic/newrelic-php-agent/blob/main/agent/php_execute.c#L393) for details on which files are used for which versions.

A note on the naming convention used: If the instrumentation for a version can be reused for a later version, you won't see a variant of the instrumentation for that version. In this case, the symfony 2 instrumentation also works for symfony 3, which is why there isn't a `fw_symfony3.c`, but there is a `fw_symfony4.c`.

**Comment by zsistla** [comment]
Hi @dragoonis , I hope @joshuabenuck's explanation helped, please let us know if more clarification is required.

**Comment by kneitinger** [comment]
Hi @dragoonis!

I'm going to close this issue due to inactivity.  Your comments and insight are still welcome though, and we're on the edge of our seats 🙂!

If you wish to continue this conversation, I'd be happy to reopen it, or you can create a new issue.

Take care!
