### ISSUE TITLE
Error collector interferes with error handling even when disabled

### ISSUE THREAD

**Issue by Starfox64** [newrelic/newrelic-php-agent#57]
## Description

When using a different error handling system (ie. Sentry), setting `newrelic.error_collector.enabled = false` does not seem to completely disable that feature. In my case, this causes Sentry to report errors twice as an Error and FatalError respectively. This does not happen when completely disabling the New Relic agent.

## Steps to Reproduce

- Setup both Sentry and New Relic in a project
- Set `newrelic.error_collector.enabled = false`
- Create an intentional PHP error
- Notice that the error is reported twice in Sentry

## Expected Behavior

New Relic should not interfere in any way with error handling when `newrelic.error_collector.enabled = false` is set.

## Relevant Logs / Console output

Issue initially filed in the Sentry repo getsentry/sentry-php#1156

The two exceptions generated
```
Error: Call to a member function test() on null
#2 /controller/Extranet/IndexController.php(50): Controller\Extranet\IndexController::show
#1 /libs/Class/Launcher.php(226): Launcher::start
#0 /index.php(6): null
```
```
Sentry\Exception\FatalErrorException: Error: Uncaught Error: Call to a member function test() on null in /var/www/controller/Extranet/IndexController.php:50
Stack trace:
#0 /var/www/libs/Class/Launcher.php(226): Controller\Extranet\IndexController->show()
#1 /var/www/index.php(6): Launcher->start()
#2 {main}
  thrown
#0 /controller/Extranet/IndexController.php(50): null
```

## Your Environment

PHP Version: 7.3.25
Agent Version: 9.14.0.290
Sentry Version: 3.1.1

## Additional context

N/A

**Comment by Starfox64** [comment]
bump

**Comment by zsistla** [comment]
Hello @Starfox64, 

Thank you for bringing this to our attention, and apologies for our overactive `stalebot`!

It appears a configuration setting might help in this case.

In general, we discourage the use of third party error handler extensions with our agent because we tend to use the same hooks into PHP internals that those extensions use.

By setting `newrelic.error_collector.enabled = false`, the PHP agent won't collect/record errors to pass up to New Relic APM UI.

In this bug report, the stated expectation is that the config setting 
```
should not interfere in any way with error handling when `newrelic.error_collector.enabled = false` is set.
This assumption is somewhat true. The setting indicates to the agent that we won’t record or collect errors, and we silently pass on the errors to whatever exception handlers exist on the stack.
```
However, in this case, their test cases triggered exceptions. Exceptions are handled with their own exception handler in PHP.

In order to disable our exception handler, it appears the following setting is needed:
`newrelic.special = no_exception_handler` 

[Sentry](https://github.com/getsentry/sentry-php/blob/master/src/ErrorHandler.php#L185) and [New Relic](https://github.com/newrelic/newrelic-php-agent/blob/main/agent/php_error.c#L221) both push all other exception_handlers on the stack, handle an exception with their own exception_handler, then pass the exception on to the other handlers. 
Based on the stack traces provided, it looks like Sentry grabs the exception, then passes it onto the New Relic exception handler (which Sentry had put on the call stack) which passes it to the Sentry error handler (which New Relic also put on the stack) again ...or something similar as the extensions step on each other's toes.

To take New Relic out of the exception handling equation, please try setting `newrelic.special = no_exception_handler` setting in the INI file.

Please let us know if this setting resolves the issue.

**Comment by Starfox64** [comment]
Thanks for the reply, that fixes the issue. I think a reference to this option would be nice in `newrelic.error_collector.enabled`'s documentation in the INI file.

**Comment by zsistla** [comment]
Glad to hear it worked for you!  We'll update the docs accordingly.
