### ISSUE TITLE
Opcache: Warning Stuck count for pid  <...>

### ISSUE THREAD

**Issue by pavel-rossinsky** [newrelic/newrelic-php-agent#590]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Warnings in opcache error log when newrelic is enabled.

```
Thu Dec  8 23:29:32 2022 (2246): Warning Stuck count for pid 2246
Thu Dec  8 23:29:32 2022 (2248): Warning Stuck count for pid 2248
Thu Dec  8 23:29:32 2022 (2247): Warning Stuck count for pid 2247
Thu Dec  8 23:29:32 2022 (2244): Warning Stuck count for pid 2244
Thu Dec  8 23:29:33 2022 (2245): Warning Stuck count for pid 2245
Thu Dec  8 23:29:33 2022 (2246): Warning Stuck count for pid 2246
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

1. Install Apache + PHP FPM.
2. Install the extension from the list below.
3. Create an index.php file with the contents:
```
<?php declare(strict_types=1);

die('test');
```
4. Configure opcache logging:
```
opcache.log_verbosity_level=4
opcache.error_log=/var/log/php/fpm_opcache.log
```
5. Run the index.php file through php-fpm.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

No warnings in the opcache error log when the newrelic extension is active.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

###  :christmas_tree: Agent version 
Reproducible on v10.3.0.315 and v10.0.0.312. I haven't tried any other versions.

### :christmas_tree: OS
`lsb_release -a`
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

### :christmas_tree: Apache version
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2022-06-23T12:51:37

### :christmas_tree: PHP Version
PHP 8.1.13 (cli) (built: Nov 26 2022 14:07:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies

### :christmas_tree: PHP Modules
[PHP Modules]
amqp
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
newrelic
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
SPX
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

### :christmas_tree: FPM Opcache config
opcache.dups_fix=1
opcache.enable_file_override=1
opcache.file_update_protection=0
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=20000
opcache.max_wasted_percentage=5
opcache.memory_consumption=512
opcache.revalidate_freq=2
opcache.revalidate_path=0
opcache.validate_permission=0
opcache.validate_timestamps=0

opcache.log_verbosity_level=4
opcache.error_log=/var/log/php/fpm_opcache.log

### :christmas_tree: Other FPM configurations
newrelic.guzzle.enabled=0
newrelic.framework="no_framework"
newrelic.framework.drupal.modules=false
newrelic.framework.wordpress.hooks=false
memory_limit=512M
realpath_cache_size=4096K
realpath_cache_ttl=1800
 

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

As soon as I set `newrelic.enabled=0` and restart fpm, warnings disappear from the opcache log.

Being activated, NewRelic slows down webshop transactions by 70-120 ms. For example, transactions that take 180 ms without NR last 275 ms when the extension is enabled. That is 35% of a slowdown. It might be related.

**Comment by bduranleau-nr** [comment]
Hi @pavel-rossinsky!

Here's where that message is output happens: https://github.com/php/php-src/blob/master/ext/opcache/ZendAccelerator.c#L2671

The `Stuck count` message is being thrown by PHP itself, see here for reasonings why php-fpm would toggle it on: https://github.com/php/php-src/blob/master/ext/opcache/ZendAccelerator.c#L3457

It's a php warning (not an error) that's probably due to increased overhead/latency (causes more race conditions) inherent in using a monitoring agent.

Overhead is an expected side effect of monitoring and reporting on software. Our engineers aim to minimize this, but your experience may differ quite a lot, depending on how you're using the agent.  If you find that you are experiencing excessive overhead, there are ways to reduce it

First, please clarify what clocksource you are using: https://discuss.newrelic.com/t/relic-solution-php-agent-cpu-overhead-tips/70182)

If that doesn't help, there are various performance knobs that can be set via the INI.

Performance knobs in the API documentation:
1. Specifies the maximum number of segments the PHP agent shall record for web transactions. Once that maximum is reached sampling will occur.
set newrelic.transaction_tracer.max_segments_web (and newrelic.transaction_tracer.max_segments_web) >= 1
2. To reduce transaction tracing details: https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-detail
set
newrelic.transaction_tracer.detail = 0
3. https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-enabled
newrelic.transaction_tracer.enabled = false
4. Increase the threshold: https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-threshold
newrelic.transaction_tracer.threshold = higher value
5. https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-explain-enabled
newrelic.transaction_tracer.explain_enabled = false
6. https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-slowsql
newrelic.transaction_tracer.slow_sql = false
7. Increase the threshold setting https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-tt-threshold
newrelic.transaction_tracer.stack_trace_threshold

**Comment by pavel-rossinsky** [comment]
Hi @bduranleau-nr. Thank you for the detailed answer. In it, I found what I was looking for, namely newrelic.transaction_tracer.max_segments_web.
I've collected some performance metrics based on the agent's configuration changes.
For each test, I ran a script that measures TTFB for 100 URLs:

Test 1. 

newrelic.enabled=0

```
Pages visited / evaluated / skipped:   100 / 86 / 14

Total time elapsed:                  13.41 s
Avg TTFB:                            155.90 ms
Avg server time with latency:        151.82 ms
Avg network latency:                 0.24 ms
Avg server time minus latency:       151.58 ms
```

Test 2.

newrelic.enabled=1

```
Pages visited / evaluated / skipped:   100 / 86 / 14

Total time elapsed:                  24.11 s
Avg TTFB:                            280.38 ms
Avg server time with latency:        275.64 ms
Avg network latency:                 0.24 ms
Avg server time minus latency:       275.40 ms
```

Test 3.

newrelic.enabled=1
newrelic.transaction_tracer.max_segments_web=2000

```
Pages visited / evaluated / skipped:   100 / 86 / 14

Total time elapsed:                  23.66 s
Avg TTFB:                            275.07 ms
Avg server time with latency:        270.97 ms
Avg network latency:                 0.24 ms
Avg server time minus latency:       270.73 ms
```

Test 4.

newrelic.enabled=1
newrelic.transaction_tracer.max_segments_web=100

```
Pages visited / evaluated / skipped:   100 / 86 / 14

Total time elapsed:                  23.48 s
Avg TTFB:                            273.02 ms
Avg server time with latency:        268.87 ms
Avg network latency:                 0.23 ms
Avg server time minus latency:       268.64 ms
```

Test 5.

newrelic.transaction_tracer.max_segments_web=100
newrelic.transaction_tracer.detail=0
newrelic.transaction_tracer.enabled=0
newrelic.transaction_tracer.slow_sql=0

```
Pages visited / evaluated / skipped:   100 / 86 / 14

Total time elapsed:                  20.21 s
Avg TTFB:                            235.06 ms
Avg server time with latency:        230.02 ms
Avg network latency:                 0.24 ms
Avg server time minus latency:       229.78 ms
```

Test 6.

newrelic.transaction_tracer.max_segments_web=100
newrelic.transaction_tracer.detail=0
newrelic.transaction_tracer.enabled=1
newrelic.transaction_tracer.slow_sql=1

```
Pages visited / evaluated / skipped:   100 / 86 / 14

Total time elapsed:                  20.19 s
Avg TTFB:                            234.79 ms
Avg server time with latency:        230.56 ms
Avg network latency:                 0.25 ms
Avg server time minus latency:       230.31 ms
```

**Comment by bduranleau-nr** [comment]
Hi @pavel-rossinsky - I'm glad to hear that we were able to help with the issue you were facing. 
Thank you for providing performance metrics as well- we do our best to balance agent performance with functionality, and these INI values are an important part of that balancing act.

Closing ticket as resolved.
