### ISSUE TITLE
PHP Agent is not pulling the latest Browser Agent during auto-inject.

### ISSUE THREAD

**Issue by vekien** [newrelic/newrelic-php-agent#718]
## Description

Agent needs to pull the latest Browser Agent when using auto-inject in order to fix:
- https://github.com/newrelic/newrelic-browser-agent/issues/599

This agent is still pulling 1.236.0 it should pull 1.237.1

## Steps to Reproduce

Enable auto-inject and check the async library being pulled.

## Expected Behavior

I expect it to pull the latest browser agent.

## Relevant Logs / Console output

n/a, it doesn't, check Network tab.

## Your Environment

- Docker
- ECS

## Additional context

Please do not tell me to restart my app.... If you do this, you don't understand how Docker/ECS works and you're wasting everyones time.

- This is a Docker env, rebuilt 100+ times in the past 2 weeks
- This is on AWS ECS, Redeployed 100+ times in the past 2 weeks
- NO CACHING
- It's happening for hundreds of users
- It's flooding Sentry with errors so it's still an issue.
- Any browser, Any computer.

**Comment by lavarou** [comment]
Hi @vekien! In order to get more information to diagnose this issue (account # and application id), we suggest filing a ticket by following the steps [here](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/#file-ticket), where we can engage our General Tech Support engineers.

If you do not have access to this support flow & the ability to open a support ticket directly, we can reach out via a post on the NR [Community Forums](https://discuss.newrelic.com/).

**Comment by vekien** [comment]
Hey, anyway this can be handled here on the actual code?

I already posted on the forums and the engineer was completely useless and didn’t read the topic, just posting a copy/paste response that was unrelated and had nothing to do with the issue, so my expectation of a competent support engineer is low.

Would rather it just be fixed by the people who write the code.

whatever deals with auto injecting the browser agent when using the PHP agent is not working and is serving an out of date version.

**Comment by lavarou** [comment]
@vekien I understand the frustration. However New Relic PHP Agent serves as a passthrough messenger between the New Relic backend and the browser and this is the reason why this issue cannot be fixed in the PHP Agent's code. The browser agent is received as the payload from the backend when PHP Agent connects to the backend (this can be checked in the daemon logs when [`newrelic.daemon.loglevel
`](https://docs.newrelic.com/docs/apm/agents/php-agent/configuration/php-agent-configuration/#inivar-daemon-loglevel) is set to `debug` - look for `Debug: command='connect'` string). Is it possible that the account or the app has the browser agent pinned to 1.236.0? This can only be verified when account # and app id are known, hence my suggestion to reach out to support as GitHub is not the place to share this sensitive information.

**Comment by vekien** [comment]
Thanks a huge  amount @lavarou i will see where my support goes!
