### ISSUE TITLE
Silent mode broken on install

### ISSUE THREAD

**Issue by pjmolina** [newrelic/newrelic-php-agent#813]
## Silent mode broken on install

Trying to automate a docker image creation with newrelic agent for PHP fails when `SILENT MODE` is used.

## Steps to Reproduce

Create the following `Dockerfile`:

```dockerfile
FROM php:8.2.14-fpm-alpine3.19 as base
# Add newrelic. Docs: https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-overview/
RUN  cd /usr/local
RUN curl -s -O https://download.newrelic.com/php_agent/release/newrelic-php5-10.15.0.4-linux-musl.tar.gz
RUN tar xzf newrelic-php5-10.15.0.4-linux-musl.tar.gz 
RUN cd newrelic-php5-10.15.0.4-linux-musl
RUN NR_INSTALL_SILENT=1 NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_KEY=TBD ./newrelic-install install 
```

Build with  `docker build .`

## Expected Behavior

Install scripts end sucessfully.

## Relevant Logs / Console output

```
    7 | >>> RUN NR_INSTALL_SILENT=1 NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_KEY=TBD ./newrelic-install install
--------------------
ERROR: failed to solve: process "/bin/sh -c NR_INSTALL_SILENT=1 NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_KEY=TBD ./newrelic-install install" did not complete successfully: exit code: 127
```

Interactive install works, silent mode fails.

## Your Environment

- OS: Windows 11 with Docker Desktop for Windows.
- Base PHP image: `php:8.2.14-fpm-alpine3.19` 
- NewRelic Agent: [newrelic-php5-10.15.0.4-linux-musl.tar.gz](https://download.newrelic.com/php_agent/release/newrelic-php5-10.15.0.4-linux-musl.tar.gz)

**Comment by pjmolina** [comment]
Looks like is working again in version: [newrelic-php5-10.16.0.5-linux-musl](https://download.newrelic.com/php_agent/release/newrelic-php5-10.16.0.5-linux-musl.tar.gz)
Did you fix this issue?

**Comment by lavarou** [comment]
Hi @pjmolina! Thanks for reaching out and providing details on your issue. However, the `Dockerfile` used to reproduce the problem has a couple of issues:

1. This layer `RUN curl -s -O https://download.newrelic.com/php_agent/release/newrelic-php5-10.15.0.4-linux-musl.tar.gz` is not future proof, because the contents of https://download.newrelic.com/php_agent/release/ always contains latest release. Therefore, once 10.16.0.5 has been published, `curl -s -O https://download.newrelic.com/php_agent/release/newrelic-php5-10.15.0.4-linux-musl.tar.gz` command will fail. If pinning version of the agent is desired, please download the agent from https://download.newrelic.com/php_agent/archive/. To reproduce the issue I changed the layer to be: `RUN curl -s -O https://download.newrelic.com/php_agent/archive/10.15.0.4/newrelic-php5-10.15.0.4-linux-musl.tar.gz`

3. This layer `RUN cd newrelic-php5-10.15.0.4-linux-musl` does not do what you think it does, i.e. change the working directory for the next command to execute. This actually is a no-op in the process of building the Docker image.

The problem you're observing, stems from the issue 2. That is, the command in this layer `RUN NR_INSTALL_SILENT=1 NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_KEY=TBD ./newrelic-install install ` does not execute in `newrelic-php5-10.15.0.4-linux-musl` directory, and therefore current working directory (`./`) does not have `newrelic-install` script, and the interpreter (`/bin/sh`) is unable to find it and exists with the code 127.

There are multiple ways to fix the problem at hand, however, following best practices of constructing container images (one of them being not embedding secrets in neither the image recipe nor in the image itself) I suggest to use the following layer to install the latest version of the agent (this method can be easily adapted to install desired version of the agent if agent version pinning is desired):

Replace
```
# Add newrelic. Docs: https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-overview/
RUN  cd /usr/local
RUN curl -s -O https://download.newrelic.com/php_agent/release/newrelic-php5-10.15.0.4-linux-musl.tar.gz
RUN tar xzf newrelic-php5-10.15.0.4-linux-musl.tar.gz 
RUN cd newrelic-php5-10.15.0.4-linux-musl
RUN NR_INSTALL_SILENT=1 NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_KEY=TBD ./newrelic-install install 
```

with
```
# Install the latest New Relic PHP Agent
RUN \
    cd /tmp \
    # Discover the latest released version && download the discovered version:
    && curl -L -o newrelic-php-agent.tar.gz "https://download.newrelic.com/php_agent/release/newrelic-php5-$(curl -s https://download.newrelic.com/php_agent/release/ | grep -o '[1-9][0-9]\?\(\.[0-9]\+\)\{3\}' | head -n1)-linux-musl.tar.gz" \
    # Install the downloaded agent:
    && tar xzf newrelic-php-agent.tar.gz \
    && NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_SILENT=0 ./*/newrelic-install install \
    # Configure the agent to use license key from NEW_RELIC_LICENSE_KEY env var:
    && sed -ie 's/[ ;]*newrelic.license[[:space:]]=.*/newrelic.license=${NEW_RELIC_LICENSE_KEY}/' $(php-config --ini-dir)/newrelic.ini \
    # Configure the agent to use app name from NEW_RELIC_APP_NAME env var:
    && sed -ie 's/[ ;]*newrelic.appname[[:space:]]=.*/newrelic.appname=${NEW_RELIC_APP_NAME}/' $(php-config --ini-dir)/newrelic.ini \
    # Cleanup temporary files:
    && rm newrelic-php-agent.tar.gz && rm -rf newrelic-php5-*-linux-musl
```

Complete `Dockerfile`:
```
FROM php:8.2.14-fpm-alpine3.19
# Install the latest New Relic PHP Agent
RUN \
    cd /tmp \
    # Discover the latest released version && download the discovered version:
    && curl -L -o newrelic-php-agent.tar.gz "https://download.newrelic.com/php_agent/release/newrelic-php5-$(curl -s https://download.newrelic.com/php_agent/release/ | grep -o '[1-9][0-9]\?\(\.[0-9]\+\)\{3\}' | head -n1)-linux-musl.tar.gz" \
    # Install the downloaded agent:
    && tar xzf newrelic-php-agent.tar.gz \
    && NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_SILENT=0 ./*/newrelic-install install \
    # Configure the agent to use license key from NEW_RELIC_LICENSE_KEY env var:
    && sed -ie 's/[ ;]*newrelic.license[[:space:]]=.*/newrelic.license=${NEW_RELIC_LICENSE_KEY}/' $(php-config --ini-dir)/newrelic.ini \
    # Configure the agent to use app name from NEW_RELIC_APP_NAME env var:
    && sed -ie 's/[ ;]*newrelic.appname[[:space:]]=.*/newrelic.appname=${NEW_RELIC_APP_NAME}/' $(php-config --ini-dir)/newrelic.ini \
    # Cleanup temporary files:
    && rm newrelic-php-agent.tar.gz && rm -rf newrelic-php5-*-linux-musl
```

Using the above Dockerfile:
1. Build the image
```
$ docker build -t newrelic/php-agent:gh-813-fixed .
```
2. Start the container and provide license key and app name as env vars:
```
$ docker run --rm -it -e NEW_RELIC_LICENSE_KEY=TBD -e NEW_RELIC_APP_NAME=containerized-instrumented-app  newrelic/php-agent:gh-813-fixed php -i | grep 'New Relic Version'
```

I hope this resolves your problem!
